### ISSUE TITLE
What's wrong with nuclear energy?

### ISSUE THREAD

**Issue by MadaraUchiha** [raisely/NoHarm#30]
## Overview
Nuclear energy is currently the cleanest and one of the most economically viable source of renewable energy available through current technology.

I mostly want to understand why it's listed.

## Proposed Resolution
Remove nuclear energy from the list of forbidden organizations/promotions allowed to use code under this licence. Alternatively, please provide an explanation on why it's there in the first place.

**Comment by tommaitland** [comment]
@MadaraUchiha There's a bit of discussion on future developments of nuclear energy [here](https://github.com/raisely/NoHarm/pull/13). The main reasons it's been excluded in the initial release (from my perspective) is:

1. Nuclear energy is a non-renewable fuel source, it requires the constant extraction of uranium
2. Nuclear energy produces highly toxic radioactive waste which is then buried in our natural environment. That waste remains radioactive for many thousands of years, and we're [not](https://edition.cnn.com/2017/05/20/us/hanford-nuclear-tank-potential-leak/index.html) [always](https://www.rt.com/usa/340234-hanford-nuclear-waste-leak-washington/) good at containing it.

I can't see nuclear energy playing a role in the energy mix of a world where we also value and protect our natural environment – especially when wind, solar, hydro and geothermal provide viable, renewable alternatives.

**Comment by MadaraUchiha** [comment]
Thanks for your answer!

1. Sure, but the scale is vastly different from other fuel-based energy generation. A few proper reactors and a few truckloads of Uranium could sustain the entire US for a year, as opposed to thousands/millions of tons of Coal or Gasoline. It's much more sustainable until we get to Geothermal energy, which is potentially the most economically viable and does not require fuel.
2. I hate to say this, but this isn't the fault of nuclear powered energy generation, it's the result of greedy businessmen cutting corners (and costs) with something they shouldn't.

I do understand your position, however, and I appreciate you taking the time to answer seriously :)

**Comment by jeznag** [comment]
Points 1 and 2 seem less relevant for fast breeder reactors that:
- produce more fissile material than they consume
- produce waste that decays in a few hundred years
https://en.wikipedia.org/wiki/Nuclear_power_proposed_as_renewable_energy
