### ISSUE TITLE
License violates OSI Open Source Definition

### ISSUE THREAD

**Issue by jwcrawley** [raisely/NoHarm#31]
## Overview
"Ethics" license based upon 3 clause BSD violates the [Open Source Definition](https://opensource.org/osd):

> 5. No Discrimination Against Persons or Groups
> 
> The license must not discriminate against any person or group of persons.
> 
> 6. No Discrimination Against Fields of Endeavor
> 
> The license must not restrict anyone from making use of the program in a specific field of endeavor. For example, it may not restrict the program from being used in a business, or from being used for genetic research.

## Proposed Resolution

Remove ethics check, or remove the claim you are open source software.

**Comment by chrisjensen** [comment]
Related to #27 
Let's put the discussion of all things OSI/FOSS/OSS in that PR
