### ISSUE TITLE
discontinue / clarify use of "open source"?

### ISSUE THREAD

**Issue by wolftune** [raisely/NoHarm#32]
(Note: I sympathize with intention of the license, please don't treat this issue as itself taking a stance on the license itself; I'm not trying to get into discussing the merits of the license itself here)

The term "open source" is really only correct when following the broad consensus around the [Open Source Definition](https://opensource.org/osd).

Your license does not meet that definition. It is closer to copyfarleft licenses in that it discriminates in some way about the users or uses.

Please either refer to your license using a different term like "shared source" or at least whenever you mention "open source" make it clear that this does *not* actually fit the definition.

**Comment by chrisjensen** [comment]
Related to #27
Let's put the discussion of all things OSI/FOSS/OSS in that PR
