### ISSUE TITLE
Junk food

### ISSUE THREAD

**Issue by jeznag** [raisely/NoHarm#34]
How about banning producers of junk food? (Not sure how to precisely define this)

**Comment by chrisjensen** [comment]
Open to this, but would need some serious consideration how to define it

**Comment by nafg** [comment]
How about processed food, bleached flour, trans fat, and takeouts?

**Comment by chrisjensen** [comment]
Baby milk formula is processed food but is a necessity. Bleached flour covers the majority of breads.

I'm assuming @milesrout's comment was sarcastic, but he highlights an important issue with these discussions: as much as there is a case to made for excluding junk food from an ethical license, aside from the issue of definition, including it in a license that excludes torture, warcrimes and the destruction of the systems that support life on earth creates a false impression of equivalency, and muddy's the waters for serious discussion of this license.
I'm not sure that time spent on trying to define and include this will be worthwhile.

**Comment by jeznag** [comment]
@chrisjensen do we need to worry about equivalency? Gambling/pornography has much less potential for harm than weapons manufacturing/fossil fuel usage - should we take them off the list :P?

How about adding a section to exclude lobbying for actions that promote obesity (e.g. advertising of "junk food" to children)?

**Comment by nafg** [comment]
Can you prove that a specific food does or does not cause obesity?

**Comment by jeznag** [comment]
There is a strong correlation between consumption of `ultra-processed foods` and obesity: https://www.sciencedirect.com/science/article/pii/S0091743515002340

and high energy density foods: https://link.springer.com/article/10.1007/s00394-014-0685-0

**Comment by milesrout** [comment]
@jeznag so? don't eat them if you don't want to get fat.
