### ISSUE TITLE
A license is not enough

### ISSUE THREAD

**Issue by clsource** [raisely/NoHarm#35]
## Overview
Hello friends. I really appreciate what you are doing here 
but this is (in my opinion) not the right way to do it.

A software license just dictates how copy, modification and distribution
will take place following copyright standards. And today we got plenty of licenses to choose from.

A software is merely a tool. Similar to a knife.
You can not control how it will be used for. It can be used for delicious food cooking
or murder. It depends on people.

And because it depends on people different moral values and ethics
will collide. So a single license would not be enough for all the use cases and different world views.
Besides that, you cannot legally obligate anyone to comply them or persecute them if they broke them so putting those conditions in a license is meaningless.

With a copyright license you can legally act *only* if they didn´t follow any of the copy, modification or distribution rules nothing more. 

The solution is not creating a new license, instead,  is better to create an example contract or [terms of service](https://en.wikipedia.org/wiki/Terms_of_service) so organizations
could adhere to higher ethics values that they consider "No Harm". In
that way you can take legal action if any of your users, customers, partners or anyone that wants to use your work does unethical activities.

## Proposed Resolution

- Use the already available licenses for software
- Create example ToS and contracts that organizations could use and customize to adhere the "No Harm"

## Futher Reading

Read this article of the [freeworldlicence](http://freeworldlicence.org/denounced.shtml) 

However, copyright law provides power only over the copying and modification of a work. 
Once someone actually has legally obtained a copy of a computer program, copyright law alone cannot restrict their right to run it. 

This meant that I could not frame The Free World Licence as a straight copyright 
licence AND include a legally binding clause that would restrict execution to free platforms only. 
The only alternative was to frame it as a commercial contract under which I could include terms of any kind.

An additional incentive for employing contract form came from an analysis of the GNU GPL's no-warranty and no-liability clauses. It turns out that, because copyright law covers only copying and modification, a straight copyright licence such as the GNU GPL does not have the power to require the end-user to agree to these terms. 

The terms are therefore advisory only; they stand as warnings, not as binding conditions of use (for the GNU GPL software end user anyway; those who distribute become bound by the GPL contract). In contrast, a commercial contract may invoke these terms as binding conditions of use. 

While warnings may be a strong enough form to ward off most legal danger, my lawyer strongly advised me to employ the contract form so as to make the no-warranty and no-liability clauses unambiguously legally binding conditions of use.

Cheers 👍

**Comment by iwwmidatlanticgdc** [comment]
Agreed, this is just one piece of a larger puzzle. But it also opens us up to other discussions, such as unionization of tech workers, and worker autonomy more broadly. Doing this this in an open-source environment can lead to doing this in a closed-source environment. And several Google employees have already protested against the use of AI in U.S. Military drones. 
Check out [Tech Workers Coalition](https://twitter.com/techworkersco) !

**Comment by chrisjensen** [comment]
Enforceability is specifically discussed in this SE answer [Software License which discriminates on 'ethical' grounds](https://softwareengineering.stackexchange.com/questions/319308/software-license-which-discriminates-on-ethical-grounds/370152#370152)

**Comment by chrisjensen** [comment]
Good suggestion @iwwmidatlanticgdc 
Maybe it's worth providing some links in the README

**Comment by clsource** [comment]
Thanks for all your comments. 
If I understand, the issue is not about enforceability, it´s more about sending a message.

The message to create a better world. And I do believe that message must be present in the tech industry both private and free/open source worlds.

I believe that if you can´t enforce the terms in the licence, then it's better to just give a blessing. In that way you could use any available licence and add a blessing. Like BSD+Blessing or MIT+Blessing or GPLv3+Blessing and so on.

Similar to what SQLite license tells (https://www.sqlite.org/different.html#license)

>  The SQLite source code contains no license since it is not governed by copyright. Instead of a license, the SQLite source code offers a blessing:

>          May you do good and not evil
>          May you find forgiveness for yourself and forgive others
>          May you share freely, never taking more than you give. 

In that blessing you could include a small text. A positive vision with higher ethical values or just a poem. A simple blessing hoping your efforts will be used for a better world. 

Another example is the Hanafuda Captain (http://www.siliconera.com/2017/01/08/hidden-message-contained-nintendo-classic-mini-famicom/) message in the Nes Mini.

> "This is the hanafuda captain speaking. Launching emulation in 3...2...1. Many efforts, tears and countless hours have been put into this jewel. So, please keep this place tidied up and don't break everything! Cheers, the hanafuda captain."

Nintendo engineers were aware that people would mess around with the Nes Mini. So they put a message for the potential hackers out there.

The No Harm clauses should be used in ways that could be enforced like I said in Terms of Use, Terms of Service and Contracts better suited for organizations that could define wich activities they will not allow if someone uses their products or services and have the resources for taking action.

👍

**Comment by clsource** [comment]
I created this repo https://github.com/blessmy/software in order to separate both approaches 👍 
I think both ways are complementary and have their use cases. So I think I can close this issue. Thanks for your comments 😄
