### ISSUE TITLE
Consider including "Universal Declaration of Human Rights"

### ISSUE THREAD

**Issue by madiko** [raisely/NoHarm#36]
Thank you for this idea. You might want to consider specifying the licence. My suggestion would be to add the Universal Declaration of Human Rights. The declaration states universal rights, many countries already have agreed upon. It includes most of the formerly issues as well:
http://www.un.org/en/universal-declaration-human-rights

**Comment by chrisjensen** [comment]
Thank you for the contribution Madiko. 
When you say add the UDHR, do you mean referencing it, or including the articles verbatim in the license?
Also, are there specific things that the UDHR covers that aren't covered by NoHarm?
@tommaitland I think you might be more familiar with the UDHR than me, do you have anything to add?

**Comment by madiko** [comment]
Hey Chris,

I meant to link / reference to it in addition to your own text. The mentioned link is in all languages, professinoally translated. Good work by the UN ;-)

Appreciate your good work and may you have a nice day,
Franziska

**Comment by chrisjensen** [comment]
Sounds like a good idea. Should we also consider referencing the [Convention on the Rights of the Child](https://www.ohchr.org/en/professionalinterest/pages/crc.aspx)?

We might need to rethink the wording of 4b. Currently it is only restricted if organisations lobby against or derive a majority of income, but in this case, I would think really we would really want to exclude any organisation that simply engages in deliberately violating or frustrating this rights.

**Comment by jeznag** [comment]
I like this idea. It would presumably then prevent usage by companies involved in ICE/Australia's offshore detention regime.
