### ISSUE TITLE
Remove "Pornography"

### ISSUE THREAD

**Issue by jamiebuilds** [raisely/NoHarm#38]
I really love the motivation behind this license, but I will not use it in it's current form because of:

> 4. This software must not be used by any organisation, website, product or service that:
>   a) lobbies for, promotes, or derives a majority of income from actions that support or contribute to:
>     - **pornography**

Sex is not harmful. Neither is pornography. Nor sex work in general. Sure there are forms of pornography/sex work which promote violence or are abusive/illegal, but banning it all together is also very harmful and dangerous.

Sex workers already have things really tough, and software has improved things a lot for them in recent years making their jobs safer and easier. Sex workers face so much violence because society tells men that they deserve it. That they are criminals and wh*res and men can take out their anger on them.

Pornography also taught me about my sexuality in a way that society failed to. It taught me that my desires were normal. That there were people like me and they weren't just the punchlines of jokes on TV. Pornography did good in my life and I'm not ashamed of that.

Please show some compassion and remove "Pornography" from your list. If you have specific objections, list those instead.

**Comment by chrisjensen** [comment]
Thanks Jamie for the note and for all you've done to get the opensource community reflect on where we stand on ethical issues.
This issue definitely needs more discussion. Let's keep all the discussion in #29 
I'm going to keep this open for now as I think this issue needs more input from people of many different backgrounds
