### ISSUE TITLE
Add "Promotion of religion"

### ISSUE THREAD

**Issue by romanr** [raisely/NoHarm#40]
Historically religion is known as the cause of most deaths, armed conflicts, persecutions. Otherwise described as "harm" which is this license is about.

**Comment by chrisjensen** [comment]
Religion, like software, is not inherently harmful, it's in the implementation choices that things go wrong.
Those things are covered under existing aspects of the license (violence, persecution).

Historically, religion has also inspired acts of great love and kindness so it would not be right to ban it in the license.
