### ISSUE TITLE
Remove "nuclear energy"

### ISSUE THREAD

**Issue by Shchvova** [raisely/NoHarm#41]
Nuclear Energy is by far safest and least toxic power source humanity has access to.
Other energy sources have dramatically larger ecological footprint (solar, wind especially).
Coal power plants lead to over a million human deaths every year.

Also, it would prevent using your software on rowers like [Curiosity](https://mars.nasa.gov/msl/mission/technology/technologiesofbroadbenefit/power/)

Edit: it would be most hypocritical or arrogant to include "nuclear" but omit coal, natural gas, solar or wind energy.

**Comment by jeznag** [comment]
See discussion in https://github.com/raisely/NoHarm/pull/13

**Comment by iwwmidatlanticgdc** [comment]
Nuclear Fission would reduce waste, but as of now there is tremendous waste, not to mention current incentives under capitalism to use nuclear energy at the detriment of public health.

**Comment by tommaitland** [comment]
Thanks for the comment @Shchvova – we do exclude fossil fuels (coal + natural gas) in 4.b of the license. The reasons nuclear has been excluded are here: #30

I haven't heard the argument before that nuclear has a smaller ecological footprint than solar and wind. Do you have peer-reviewed research you can point to that substantiates that?

**Comment by dbwiddis** [comment]
> I haven't heard the argument before that nuclear has a smaller ecological footprint than solar and wind. Do you have peer-reviewed research you can point to that substantiates that?

Not the OP but stumbled on this issue and figured I'd look it up.  [This peer-reviewed research](https://www.nature.com/articles/s41560-017-0032-9) is summarized [in this article](https://www.carbonbrief.org/solar-wind-nuclear-amazingly-low-carbon-footprints).  Quoting from the summary, as I do not have direct access to the article:
> The study finds each kilowatt hour of electricity generated over the lifetime of a nuclear plant has an emissions footprint of 4 grammes of CO2 equivalent (gCO2e/kWh). The footprint of solar comes in at 6gCO2e/kWh and wind is also 4gCO2e/kWh.

While the nuclear/wind show equality at this unit, visual inspection of the graphic does appear to show nuclear is lower.  So I believe @Shchvova's claim of "lower" is true in both cases.
![image](https://user-images.githubusercontent.com/9291703/85332982-b2b7cd80-b48d-11ea-974a-cb4264242121.png)
