### ISSUE TITLE
Consider include agrochemicals

### ISSUE THREAD

**Issue by pedrolucasp** [raisely/NoHarm#44]
## Overview
In Brazil we have a increasing amount of politicians and companies lobbying to increase and help to spread agrochemicals use in general agriculture.

We all know that agrochems is not healthy and there's plenty of research to prove that damages people's life. 

Globally we have a very increasing movement of people working with organic food production.

## Proposed Resolution

We include agrochemicals that cause potential damage to people's life. The problem with that is there's some agrochemicals that don't cause damage.

Any other ideas of how can we embrace this?

**Comment by jeznag** [comment]
This would need to be nuanced. Some agrochemicals like neonicotinides do have strong evidence of negative impacts on bee populations/human health. Other chemicals have a net benefit and are vital for ensuring we can feed the world's growing population. The [organic yield gap](http://www.pnas.org/content/114/5/926/) makes me reluctant to advocate against non-organic agriculture.

**Comment by tommaitland** [comment]
Going to close this for now as the issue has gone quite stale, and I agree with @jeznag that this would require a good amount of nuance. Open to someone proposing wording if it comes up again.
