### ISSUE TITLE
Rename master branch to something less offensive

### ISSUE THREAD

**Issue by femperi** [raisely/NoHarm#55]
## Overview

The use of the word "master" can be triggering to some individuals, if this project is really about "no harm" this repository should set an example.

## Proposed Resolution

Rename the master branch to something less triggering like, head, edge or main.

**Comment by Sentoki** [comment]
I thing that word "head" can offend some people with brain damage, of some head/face damages after some accident. And word "main" can offence passive people.

**Comment by jeznag** [comment]
@femperi can you post links to a case for removing master? I've seen compelling arguments for removing master + slave but master on its own doesn't necessarily have negative connotations. One can master a skill or master one's weaknesses for example.

**Comment by femperi** [comment]
Python, Redis etc have all removed the term as it's incredibly racist towards people of color.
Also I've managed to land the change in Contributors Covenant, an inclusive project.

**Comment by jeznag** [comment]
@femperi wasn't that more about removing `slave`?

**Comment by chrisjensen** [comment]
As someone not affected by slavery personally or in my family history, I'm not in a position to comment on how big a deal this is, it's a simple change to make so i'm happy to err on the side of caution and grant the change.

**Comment by f1yn** [comment]
Hey @femperi, just wanted to let you know that we've changed the default branch to `publish`
