### ISSUE TITLE
Include UDHR (and maybe an interpretation) in the license

### ISSUE THREAD

**Issue by chrisjensen** [raisely/NoHarm#59]
## Overview
If the code is shared in countries where the UDHR is blocked by firewalls, then users are unable to understand the license.
We may also want to add greater level of specificity, as the UDHR is interpreted differently by different nations.

**Comment by barraponto** [comment]
I guess UDHR should be included in the license making it a bit more interesting to use in UDHR-blocker countries.

**Comment by tommaitland** [comment]
Included in #59
