### ISSUE TITLE
Clarification of personal views

### ISSUE THREAD

**Issue by Esmala** [raisely/NoHarm#60]
Hi! Why is nuclear energy classed as a bad "thing". The license looks ok otherwise. It would be cool to have projects like this with unbiased views. There have been only three major nuclear accidents during the history of nuclear energy. Burning coal for example is a far worse thing, than using nuclear energy. The industries will not accept using solar or wind power in the near future, so it would be unwise to discriminate nuclear power as it's a CO2 free form of energy. Please do not talk about evil corporations, i understand the point, but it makes a project like this biased. You probably get it; the license looks like an expression of personal opinion.

**Comment by chrisjensen** [comment]
Nuclear has been discussed in #41 #30 and #13
