### ISSUE TITLE
Allow license users to opt-in or out of specific cases.

### ISSUE THREAD

**Issue by jimsynz** [raisely/NoHarm#63]
## Overview
Having read through the open issues on this repository there's a lot of issues titled "consider adding X", and there's always going to be disagreement between license users about which issues are hard lines for them and which they're okay with.

## Proposed Resolution
My proposal is to move the list of specific activities which license users wish to avoid into a separate appendix which is referenced in the license and change point 4 of the license to something like:

> This software must not be used by any organisation, website, product or service in breach of sections A; 1-3,6,9-11 and 15 and B of APPENDIX A of this license available at raisely/NoHarm/APPENDIX_A.md

This way we can give everyone the ability to submit additional activities to be prohibited by license without forcing the license version to be revved every time something is added or removed.

**Comment by chrisjensen** [comment]
I appreciate the thought behind this, but suspect this may be unworkable in practice.
How would one document the license (and compatability/incompatability) for use with something like [license checker](https://www.npmjs.com/package/license-checker)?

Would projects list NoHarm-A1-3,6,9 in the project license?
