### ISSUE TITLE
Consider add Alcohol

### ISSUE THREAD

**Issue by trocol** [raisely/NoHarm#65]
## Overview

Alcohol is a very pernicious substance, that generates :
* harmful effects on your body (liver, brain, stomach, etc.)
* great physical addiction
* serious social issues (violence, suicide and depression, property damage, date rape, etc.)

The companies selling those products are aware of the **damage they're generating on society**, and they not only keep selling, but they spend great amounts of money to advertise their products through lies and manipulation (specially to the younger targets possible in order to create addiction that would keep them as future clients).

With those facts we can consider that alcohol is way worse than tobacco: at least both are bad for the body and create addiction, but alcohol also is behind lots of social problems we face day to day.

## Proposed Resolution

The license should restrict companies that live from selling alcohol from using the licensed work, by adding `alcohol` on the banned activities on the section 5 list.

**Comment by jeznag** [comment]
I also raised this but there was concern it would dampen adoption of the license.

**Comment by chrisjensen** [comment]
Yes, although alcohol is certainly an industry that creates harm, and I personally would be inclined to deny it's usage, that's not a view that's widely accepted in many cultures and so in the interests of keeping the license adoptable, we're leaving it out.
Feel free to fork though 😉
