### ISSUE TITLE
"burning of forests"

### ISSUE THREAD

**Issue by willow385** [raisely/NoHarm#66]
## Overview
The license forbids the use of software for "the burning of forests". But what about [controlled burning](https://en.wikipedia.org/wiki/Controlled_burn), which is used to *maintain* the health of ecosystems?

## Proposed Resolution
Change the "burning of forests" line to say something like "burning of forests, except for controlled burning where required to maintain the health of an ecosystem or mitigate danger".

**Comment by tommaitland** [comment]
In an update I've just published, we've reworded this to: `the destruction of habitats for threatened or endangered species, including through deforestation or burning of forests`.

This should resolve this concern and allow for burning where required to a maintain the health of an ecosystem.
