### ISSUE TITLE
Nuclear Energy?

### ISSUE THREAD

**Issue by tsteinholz** [raisely/NoHarm#68]
Despite discussions in #41 #30 and #13 Nuclear Energy is still listed as prohibited with no caveats.

I can understand the nuclear energy is not perfect: management of nuclear waste, supply chain dependance, and other potential dangers surrounding mismanagement. Just because it is powerful does not make it inherently evil. Realistically, our approaches to nuclear waste are still extremely naive and have much room to grow in efficiency, re-use of waste, safety (passive reactors) - this research should be supported!

The way this is written would currently exclude the following institutions from using software published with the license...

- Research Laboratories (ex: [UC: Lawrence Berkeley National Laboratory](https://visits.lbl.gov/))
- Space Companies ([NASA, SpaceX, and more](https://en.wikipedia.org/wiki/Nuclear_power_in_space))
- And much more.....

**Resolution**
The "nuclear energy" clause should be changed to "Weapons of Mass Destruction" https://en.wikipedia.org/wiki/Weapon_of_mass_destruction -- Which would also include chemical and biological warfare, which was not previously mentioned at all.

**Comment by agucova** [comment]
Totally agree with this. I was surprised to find this in the license!

**Comment by programmerPhysicist** [comment]
In some cases, nuclear energy technology _saves_ lives. Certain radioactive isotopes are extracted from reactors to use in cancer treatment, or for imaging the body: https://www.britannica.com/story/how-radioactive-isotopes-are-used-in-medicine. Than there is the case of, if you replace a fossil fuel power plant with a nuclear power plant, fewer people will die of air pollution.

People may be unaware that the Curiosity rover, and other NASA missions uses nuclear energy, in the form of radioisotope thermoelectric generator (RTG). The radioactive isotopes in RTGs, or nuclear batteries as they are also known, require nuclear reactors to produce them.

**Comment by MrAureliusR** [comment]
I was also very surprised to see this in the license. This essentially means that this license burdens those fighting climate change, which is the exact opposite of the intended effect of the license. Nuclear energy is (almost certainly) going to be the most important technology for generating power in the next 50-100 years. It can be done safely & responsibly. Look at the CANDU reactors, for example -- they are all over the world, have an outstanding safety record, and are very efficient. 

Until this clause is removed, I simply cannot in good conscience use this license for my projects. I would just remove that from the list, but changing licenses is something I've always read should be avoided.

Please reconsider changing it to Weapons of mass destruction, as suggested by @tsteinholz

**Comment by ghost** [comment]
[Nuclear energy is not as deadly as other forms of energy production](https://youtu.be/Jzfpyo-q-RM) (both renewable and non-renewable sources). Weapons of mass destruction are already covered in the license with other forms of unprovoked violence.

I think this discussion can end here.

**Comment by MrAureliusR** [comment]
This seems to have been changed in the most recent version of the license, so this issue can be closed! And now I can use this license, yay!

**Comment by ghost** [comment]
@tsteinholz or @tommaitland, do you mind closing this, please? This issue has been resolved.

**Comment by Brandon-Huu** [comment]
No wonder this hasn't been finished after five years.

The people who thought this up were actual bottom feeders
