### ISSUE TITLE
[Discussion] Composing a license

### ISSUE THREAD

**Issue by ghost** [raisely/NoHarm#77]
## Overview
As of the time of writing, I have an implementation on creating a license from scratch. The idea came from [my comment on this issue](https://github.com/raisely/NoHarm/issues/14#issuecomment-1193493652).

## Proposed Resolution
I would like the Raisely team to oversee my progress on [my fork](https://github.com/IRod22/NoHarm/tree/templates) and see how it can be improved, which is why I opened this issue.

**Comment by tommaitland** [comment]
@IRod22 Can you link me to the file you've changed, or even pull request in so we can see and comment on the diff?

**Comment by ghost** [comment]
@tommaitland On it. Do you mind if it's a draft PR?

**Comment by tommaitland** [comment]
Draft PRs are fine! Thanks for submitting, will give some feedback in the next few days. Will close this issue in favour of the PR.
