### ISSUE TITLE
What does “different licence for derivative works” mean?

### ISSUE THREAD

**Issue by realpixelcode** [raisely/NoHarm#78]
> You may add Your own copyright statement to Your modifications and may provide additional or different license terms and conditions for use, reproduction, or distribution of Your modifications, or 
>
> ***for any such Derivative Works as a whole***, 
>
> provided Your use, reproduction, and distribution of the Work otherwise complies with the conditions stated in this License.

Should this be understood as `a)` or as `b)`?

- a) You may choose a different licence.
- b) You may choose a different licence for your modifications, but unchanged parts of the original work must remain under the Do No Harm Licence.

If it's meant like `b)`, I think it should be clarified more.

**Comment by tommaitland** [comment]
This is pulled directly from the Apache 2.0 license and therefore I don't think we should change it. See: https://www.apache.org/licenses/LICENSE-2.0
