### ISSUE TITLE
Similarity to Just World Hypothesis

### ISSUE THREAD

**Issue by chrisjensen** [raisely/NoHarm#9]
The name could be associated with the [Just World Hypothesis](https://en.wikipedia.org/wiki/Just-world_hypothesis).

Everyone get's what they deserve ie rich people and poor people are that way because of their decisions, not systemic failure.

Not the best association for a license with a progressive bent :-/

**Comment by LuxLang** [comment]
Good observation.

Hadn't thought about it.

How about "Better World License"? "Fair World License"? "Do Good License"? "Only Do Good License"?

**Comment by chrisjensen** [comment]
Credit where credit is due: [source](https://www.reddit.com/r/opensource/comments/8g4sun/why_we_need_an_ethical_open_source_license/dy9q08a/?context=2)

The "Do No Harm License"?

Also, all the discussion in #1

**Comment by LuxLang** [comment]
> The "Do No Harm License"?

Sounds good.

**Comment by tommaitland** [comment]
The "Humanitarian License"?

This is a can of worms.

**Comment by LuxLang** [comment]
I like "Ethical World License".

It was previously proposed by @tommaitland in #1.

I think the name describes the intent of the license very well.

**Comment by chrisjensen** [comment]
> The problem with harm (or violence) is that it can sometimes be justifiable.

Surgeons cut people open to heal them, but still use the Hippocratic oath. ;-)

The no harm license is conceptually really easy to understand

**Comment by LuxLang** [comment]
Let's say there's a group engaging in protests, and using/developing software under the JWL (perhaps for communicating among themselves securely).

A no-violence clause in the license would mean they can only do peaceful/non-violent resistance.

Not everybody agrees to that strategy: https://www.amazon.com/Nonviolence-Protects-State-Peter-Gelderloos/dp/0896087727

**Comment by chrisjensen** [comment]
Let's keep this issue to discussion of the name. As to weather to restrict violence in the license, can you open another issue for this?

On the name, I'm still leaning towards the "Do No Harm License"

The things I think this name has going for it:
* The framing of the Hippocratic oath is well accepted
* The core notion is easy to comprehend at first glance
* The short name could be `NoHarm`, much easier to get the gist than JWL or EWL

Ethical carries a lot of baggage as society has adopted the view that "Ethical" = gray.
The knee jerk reaction to ethical is "who decides", I think this is a harder argument to make with "do no harm"

**Comment by ama-gi** [comment]
I propose "Social Justice Warrior License". Since this is exactly what this is.

**Comment by LuxLang** [comment]
Just saw this and thought it might be indirectly relevant to this discussion:
https://www.acm.org/code-of-ethics
